### ISSUE TITLE
ZKAccess panel becomes unresponsibe and eventually unavailable in HASS

### ISSUE THREAD

**Issue by vwout** [vwout/hass-zkaccess_c3#8]
Hi Vwout, By way of update I have disabled ZKAccess and the problem persists. I lose ability to control doors after about 24 hours and the status does not update.

As soon as I restart HA control and status comes back so it is not the panel.

It starts off very responsive then seems to become laggy and slow as time passes before eventually becoming completely unresponsive.

Let me know what you would need from me?

_Originally posted by @benofishal in https://github.com/vwout/hass-zkaccess_c3/issues/6#issuecomment-1935005139_

See logs in https://github.com/vwout/hass-zkaccess_c3/issues/6#issuecomment-1935026150 and https://github.com/vwout/hass-zkaccess_c3/issues/6#issuecomment-1935982685

**Comment by benofishal** [comment]
Hi vwout long time. I wonder whether you may have time to look further into this issue as I'd love to get this working properly. My use case is mainly to open the garage door from my van android auto display and it's a shame this works for a short period then becomes unresponsive. I'm happy to provide a financial donation for your time if that is of interest. Thanks for all your hard work so far with this integration.

**Comment by vwout** [comment]
Thanks, for the appreciation and the offer. Feel free to express your appreciation by a donation to charity. This is a hobby project and I'd like to keep it that way :)

What was the last version you tested? I did work on the connection handling quite a bit when you reported the issues. My latest improvements have happened after your last comment. I did notice improved stability in my own setup. I just released those improvements as release [0.0.9](https://github.com/vwout/hass-zkaccess_c3/releases/tag/0.0.9).

**Comment by benofishal** [comment]
OK understood and happy to donate as you wish.

I think I noticed you had made some changes after and downloaded the changed files and imported to by HA but did not solve for me.

I'll try your latest release now, perhaps I missed something or did something wrong.

Thanks and I'll let you know.

**Comment by sav94rus** [comment]
Good afternoon Good idea. I want to integrate. I have a c2-260 panel. Can I do this with her? The panel is controlled. But when I try to enter the host address, it displays Failed to connect. What could this be connected with? Thank you.

**Comment by vwout** [comment]
> Good afternoon Good idea. I want to integrate. I have a c2-260 panel. Can I do this with her? The panel is controlled. But when I try to enter the host address, it displays Failed to connect. What could this be connected with? Thank you.

I created a new issue to track your request.

**Comment by benofishal** [comment]
Hi vwout, long time checking in. Since your last update the time online has improved but does still die eventually requiring a full HA restart to regain status and lock control. Unsure why this happens. How is it your end do you still have loss of control after a period. I think my time is anywhere between 24-48 hours.

Do you know if there is a way to restart your integration without having to restart the whole HA, something I could perhaps automate and schedule?

**Comment by benofishal** [comment]
Happy to provide any further debug and testing if desired. Hope all is well.

**Comment by vwout** [comment]
Hi, I'm running latest (0.0.9) on my setup. I'm also still facing occasional issues. Sometimes this requires a HA restart, sometimes a panel restart. My setup sometimes runs for weeks without permanently losing the connection. I haven't figured out the definitive cause unfortunately.
